import { describe, expect, test } from "bun:test";

import { checkFrontmatter, AGENT_SKILLS_KEYS, HOST_GENERATED_KEYS } from "../src/validation/frontmatter.ts";
import { BUDGETED, checkBudget, SKILL_LINE_WARN, SKILL_LINE_FAIL } from "../src/validation/budget.ts";
import { loadCatalog } from "../src/catalog/load.ts";
import { makeTree } from "./helpers/tree.ts";

function ctxFor(skillFiles: Record<string, string>, ids: string[] = ["alpha"]) {
  const root = makeTree({
    "catalog.yaml": `schema_version: 1\npackage:\n  id: ak\n  name: agent-kit\n  version: 0.1.0\n  namespace: "/ak:"\n  default_profile: core\nskills:\n${ids
      .map((id) => `  - id: ${id}\n    status: authored\n    invocation: U\n`)
      .join("")}`,
    ...skillFiles,
  });
  const { catalog } = loadCatalog(root);
  if (catalog === null) throw new Error("fixture has no catalog");
  return { root, catalog };
}

const OK = "---\nname: alpha\ndescription: Use when the caller asks for a thing.\n---\n\n# Alpha\n\nBody.\n";

describe("canonical SKILL.md frontmatter", () => {
  test("the Agent Skills key set is exactly name, description, license, metadata", () => {
    expect([...AGENT_SKILLS_KEYS].sort()).toEqual(["description", "license", "metadata", "name"]);
  });

  test("the host-generated key set is the three the packager emits", () => {
    expect([...HOST_GENERATED_KEYS].sort()).toEqual(["allowed-tools", "argument-hint", "disable-model-invocation"]);
  });

  test("a canonical file with only spec keys passes", () => {
    const ctx = ctxFor({ "skills/alpha/SKILL.md": OK });
    expect(checkFrontmatter(ctx)).toEqual([]);
  });

  test("license and metadata are allowed", () => {
    const ctx = ctxFor({
      "skills/alpha/SKILL.md": "---\nname: alpha\ndescription: d\nlicense: MIT\nmetadata:\n  a: b\n---\nbody\n",
    });
    expect(checkFrontmatter(ctx)).toEqual([]);
  });

  test.each(["disable-model-invocation: true", "argument-hint: <pr>", "allowed-tools: [Read]"])(
    "a hand-written host key (%s) in a canonical file is an error naming the key and its line",
    (line) => {
      const ctx = ctxFor({ "skills/alpha/SKILL.md": `---\nname: alpha\ndescription: d\n${line}\n---\nbody\n` });
      const issue = checkFrontmatter(ctx).find((i) => i.rule === "frontmatter.host-key-in-canonical");
      expect(issue?.severity).toBe("error");
      expect(issue?.line).toBe(4);
      expect(issue?.message).toContain("generated by the packager");
    },
  );

  test("name must equal the directory name", () => {
    const ctx = ctxFor({ "skills/alpha/SKILL.md": "---\nname: not-alpha\ndescription: d\n---\nbody\n" });
    const issue = checkFrontmatter(ctx).find((i) => i.rule === "frontmatter.name-mismatch");
    expect(issue?.severity).toBe("error");
    expect(issue?.message).toContain("not-alpha");
    expect(issue?.message).toContain("alpha");
  });

  test("an unknown non-host key is an error", () => {
    const ctx = ctxFor({ "skills/alpha/SKILL.md": "---\nname: alpha\ndescription: d\nversion: 2\n---\nbody\n" });
    expect(checkFrontmatter(ctx).some((i) => i.rule === "frontmatter.unknown-key")).toBe(true);
  });

  test("missing frontmatter is an error", () => {
    const ctx = ctxFor({ "skills/alpha/SKILL.md": "# Alpha\n" });
    expect(checkFrontmatter(ctx).some((i) => i.rule === "frontmatter.missing")).toBe(true);
  });

  test("missing name or description is an error", () => {
    const ctx = ctxFor({ "skills/alpha/SKILL.md": "---\nname: alpha\n---\nbody\n" });
    const issue = checkFrontmatter(ctx).find((i) => i.rule === "frontmatter.missing-required-key");
    expect(issue?.message).toContain("description");
  });

  test("a skill with no SKILL.md yet is silent here; completeness owns that", () => {
    expect(checkFrontmatter(ctxFor({}))).toEqual([]);
  });

  test("malformed frontmatter YAML is reported, not thrown", () => {
    const ctx = ctxFor({ "skills/alpha/SKILL.md": "---\nname: [unclosed\n---\nbody\n" });
    expect(checkFrontmatter(ctx).some((i) => i.rule === "frontmatter.unparseable")).toBe(true);
  });
});

describe("instruction budget", () => {
  test("the limits are AUTHORING.md's: warn over 150, fail over 300", () => {
    expect(SKILL_LINE_WARN).toBe(150);
    expect(SKILL_LINE_FAIL).toBe(300);
  });

  test("the sections the budget governs are exactly the three AUTHORING.md names", () => {
    // §12.5: "`BUDGETED` measures skills, protocols and roles, and a reference
    // pack is deliberately absent from it." That sentence is a claim about this
    // value, and it is load-bearing -- §12.5 spends the following paragraph
    // explaining why a reference pack is exempt from §1's numbers.
    //
    // The three sections named are each covered behaviourally below and in
    // bodies.test.ts, so dropping one already fails something. Adding a fourth
    // does not: appending a `references` row to BUDGETED makes §12.5's sentence
    // false, and with this pin removed the suite stays green. Measured, not
    // assumed. This assertion is the only thing standing between that edit and
    // a passage that no longer describes the code.
    expect(BUDGETED.map((b) => b.section)).toEqual(["skills", "protocols", "roles"]);
  });

  test("a short skill body produces nothing", () => {
    expect(checkBudget(ctxFor({ "skills/alpha/SKILL.md": OK }))).toEqual([]);
  });

  test("over the warn limit is a warning", () => {
    const body = `---\nname: alpha\ndescription: d\n---\n${"line\n".repeat(SKILL_LINE_WARN + 1)}`;
    const issues = checkBudget(ctxFor({ "skills/alpha/SKILL.md": body }));
    expect(issues[0]?.severity).toBe("warning");
    expect(issues[0]?.rule).toBe("budget.skill-over-target");
  });

  test("over the hard cap is an error", () => {
    const body = `---\nname: alpha\ndescription: d\n---\n${"line\n".repeat(SKILL_LINE_FAIL + 1)}`;
    const issues = checkBudget(ctxFor({ "skills/alpha/SKILL.md": body }));
    expect(issues[0]?.severity).toBe("error");
    expect(issues[0]?.rule).toBe("budget.skill-over-cap");
    expect(issues[0]?.message).toContain(String(SKILL_LINE_FAIL));
  });

  test("exactly at the warn limit is clean", () => {
    const body = `---\nname: alpha\ndescription: d\n---\n${"line\n".repeat(SKILL_LINE_WARN - 4)}`;
    expect(checkBudget(ctxFor({ "skills/alpha/SKILL.md": body }))).toEqual([]);
  });
});

/**
 * §12 says §1 applies to protocol and role bodies unchanged, and the budget
 * check read only `SKILL.md`. The cost was concrete: a 151-line protocol body
 * got a formal exception record written for a threshold the validator never
 * applied to it.
 */
describe("the line budget reaches every body §1 governs", () => {
  function bodyCtx(files: Record<string, string>) {
    const root = makeTree({
      "catalog.yaml": `schema_version: 1\npackage:\n  id: ak\n  name: agent-kit\n  version: 0.1.0\n  namespace: "/ak:"\n  default_profile: core\nprotocols:\n  - id: alpha\n    status: authored\nroles:\n  - id: beta\n    status: authored\n`,
      ...files,
    });
    const { catalog } = loadCatalog(root);
    if (catalog === null) throw new Error("fixture has no catalog");
    return { root, catalog };
  }

  test("a protocol body over the target is a warning, as §1 says it is", () => {
    const issues = checkBudget(bodyCtx({ "protocols/alpha/PROTOCOL.md": "line\n".repeat(SKILL_LINE_WARN + 1) }));
    expect(issues[0]?.rule).toBe("budget.body-over-target");
    expect(issues[0]?.severity).toBe("warning");
    expect(issues[0]?.file).toBe("protocols/alpha/PROTOCOL.md");
  });

  test("a role body over the hard cap is an error", () => {
    const issues = checkBudget(bodyCtx({ "roles/beta/ROLE.md": "line\n".repeat(SKILL_LINE_FAIL + 1) }));
    expect(issues[0]?.rule).toBe("budget.body-over-cap");
    expect(issues[0]?.severity).toBe("error");
  });

  test("a body inside the target produces nothing", () => {
    expect(checkBudget(bodyCtx({ "protocols/alpha/PROTOCOL.md": "line\n".repeat(20) }))).toEqual([]);
  });
});

/**
 * A body is measured in lines, and every budget fixture above hides the
 * difference between a line and a newline.
 *
 * `lineCount` corrects for a trailing newline: `split("\n")` over text that
 * ends in one yields a final empty element that is not a line. Delete the
 * correction -- `return lines.length - 1`, which is what `wc -l` counts -- and
 * all six tests above stay green, because `"line\n".repeat(n)` ends in a
 * newline and that is the single shape where the two spellings agree.
 *
 * The fixtures below are the other shape. n lines with no final newline split
 * into n elements, none of them empty, so the corrected count is n and the
 * uncorrected count is n - 1. At the target that is the difference between a
 * row and no row: not a wrong severity and not a wrong number, the finding
 * simply absent, which is the failure mode nobody goes looking for. At the cap
 * it is quieter still -- the body lands back in the warn band and an error
 * downgrades to a warning.
 *
 * This is not hypothetical arithmetic. `protocols/review-delta/PROTOCOL.md` is
 * 151 lines at fef4709, one line over the target, and is reported today.
 * Measured on a clean extract at that revision over both spellings and both
 * body shapes: the correct spelling reports it whether or not the file ends in
 * a newline -- that insensitivity is the entire job of the correction -- while
 * `lines.length - 1` reports it with the newline and goes silent without it.
 * Three of those four cells print the row; the silent one is the defect meeting
 * a file that lost its last byte, and nothing here requires a file to end in one.
 *
 * So these fixtures deliberately omit the final newline, and the first test
 * asserts the omission. Restoring it to match the style above would leave two
 * tests that pass under both spellings and guard nothing.
 */
describe("a body is measured by its lines, not by its newlines", () => {
  /** n lines, the last one unterminated. */
  function unterminated(n: number): string {
    return `${"line\n".repeat(n - 1)}line`;
  }

  function ctx(files: Record<string, string>) {
    const root = makeTree({
      "catalog.yaml": `schema_version: 1\npackage:\n  id: ak\n  name: agent-kit\n  version: 0.1.0\n  namespace: "/ak:"\n  default_profile: core\nprotocols:\n  - id: alpha\n    status: authored\nroles:\n  - id: beta\n    status: authored\n`,
      ...files,
    });
    const { catalog } = loadCatalog(root);
    if (catalog === null) throw new Error("fixture has no catalog");
    return { root, catalog };
  }

  test("the fixtures are the shape under test: n lines, no trailing newline", () => {
    // The positive control. Both assertions below are about what the check
    // does with an unterminated body, and neither can discriminate if the
    // fixture quietly stops being unterminated.
    const body = unterminated(SKILL_LINE_WARN + 1);
    expect(body.endsWith("\n")).toBe(false);
    expect(body.split("\n")).toHaveLength(SKILL_LINE_WARN + 1);
    expect(body.split("\n").at(-1)).toBe("line");
  });

  test("one line over the target is reported even with no final newline", () => {
    const issues = checkBudget(ctx({ "protocols/alpha/PROTOCOL.md": unterminated(SKILL_LINE_WARN + 1) }));
    expect(issues).toHaveLength(1);
    expect(issues[0]?.severity).toBe("warning");
    expect(issues[0]?.rule).toBe("budget.body-over-target");
    // The count, not just the row: a check that fires on the right file for
    // the wrong number is the same defect one step further along.
    expect(issues[0]?.message).toContain(`${SKILL_LINE_WARN + 1} lines`);
  });

  test("one line over the cap stays an error and does not decay to a warning", () => {
    const issues = checkBudget(ctx({ "roles/beta/ROLE.md": unterminated(SKILL_LINE_FAIL + 1) }));
    expect(issues).toHaveLength(1);
    expect(issues[0]?.severity).toBe("error");
    expect(issues[0]?.rule).toBe("budget.body-over-cap");
    expect(issues[0]?.message).toContain(`${SKILL_LINE_FAIL + 1} lines`);
  });
});
