import { describe, expect, test } from "bun:test";

import { checkFrontmatter, AGENT_SKILLS_KEYS, HOST_GENERATED_KEYS } from "../src/validation/frontmatter.ts";
import { checkBudget, SKILL_LINE_WARN, SKILL_LINE_FAIL } from "../src/validation/budget.ts";
import { loadCatalog } from "../src/catalog/load.ts";
import { makeTree } from "./helpers/tree.ts";

function ctxFor(skillFiles: Record<string, string>, ids: string[] = ["alpha"]) {
  const root = makeTree({
    "catalog.yaml": `schema_version: 1\npackage:\n  id: ak\n  name: agent-kit\n  version: 0.1.0\n  namespace: "/ak:"\n  default_profile: core\nskills:\n${ids
      .map((id) => `  - id: ${id}\n    status: authored\n    invocation: U\n`)
      .join("")}`,
    ...skillFiles,
  });
  const { catalog } = loadCatalog(root);
  if (catalog === null) throw new Error("fixture has no catalog");
  return { root, catalog };
}

const OK = "---\nname: alpha\ndescription: Use when the caller asks for a thing.\n---\n\n# Alpha\n\nBody.\n";

describe("canonical SKILL.md frontmatter", () => {
  test("the Agent Skills key set is exactly name, description, license, metadata", () => {
    expect([...AGENT_SKILLS_KEYS].sort()).toEqual(["description", "license", "metadata", "name"]);
  });

  test("the host-generated key set is the three the packager emits", () => {
    expect([...HOST_GENERATED_KEYS].sort()).toEqual(["allowed-tools", "argument-hint", "disable-model-invocation"]);
  });

  test("a canonical file with only spec keys passes", () => {
    const ctx = ctxFor({ "skills/alpha/SKILL.md": OK });
    expect(checkFrontmatter(ctx)).toEqual([]);
  });

  test("license and metadata are allowed", () => {
    const ctx = ctxFor({
      "skills/alpha/SKILL.md": "---\nname: alpha\ndescription: d\nlicense: MIT\nmetadata:\n  a: b\n---\nbody\n",
    });
    expect(checkFrontmatter(ctx)).toEqual([]);
  });

  test.each(["disable-model-invocation: true", "argument-hint: <pr>", "allowed-tools: [Read]"])(
    "a hand-written host key (%s) in a canonical file is an error naming the key and its line",
    (line) => {
      const ctx = ctxFor({ "skills/alpha/SKILL.md": `---\nname: alpha\ndescription: d\n${line}\n---\nbody\n` });
      const issue = checkFrontmatter(ctx).find((i) => i.rule === "frontmatter.host-key-in-canonical");
      expect(issue?.severity).toBe("error");
      expect(issue?.line).toBe(4);
      expect(issue?.message).toContain("generated by the packager");
    },
  );

  test("name must equal the directory name", () => {
    const ctx = ctxFor({ "skills/alpha/SKILL.md": "---\nname: not-alpha\ndescription: d\n---\nbody\n" });
    const issue = checkFrontmatter(ctx).find((i) => i.rule === "frontmatter.name-mismatch");
    expect(issue?.severity).toBe("error");
    expect(issue?.message).toContain("not-alpha");
    expect(issue?.message).toContain("alpha");
  });

  test("an unknown non-host key is an error", () => {
    const ctx = ctxFor({ "skills/alpha/SKILL.md": "---\nname: alpha\ndescription: d\nversion: 2\n---\nbody\n" });
    expect(checkFrontmatter(ctx).some((i) => i.rule === "frontmatter.unknown-key")).toBe(true);
  });

  test("missing frontmatter is an error", () => {
    const ctx = ctxFor({ "skills/alpha/SKILL.md": "# Alpha\n" });
    expect(checkFrontmatter(ctx).some((i) => i.rule === "frontmatter.missing")).toBe(true);
  });

  test("missing name or description is an error", () => {
    const ctx = ctxFor({ "skills/alpha/SKILL.md": "---\nname: alpha\n---\nbody\n" });
    const issue = checkFrontmatter(ctx).find((i) => i.rule === "frontmatter.missing-required-key");
    expect(issue?.message).toContain("description");
  });

  test("a skill with no SKILL.md yet is silent here; completeness owns that", () => {
    expect(checkFrontmatter(ctxFor({}))).toEqual([]);
  });

  test("malformed frontmatter YAML is reported, not thrown", () => {
    const ctx = ctxFor({ "skills/alpha/SKILL.md": "---\nname: [unclosed\n---\nbody\n" });
    expect(checkFrontmatter(ctx).some((i) => i.rule === "frontmatter.unparseable")).toBe(true);
  });
});

describe("instruction budget", () => {
  test("the limits are AUTHORING.md's: warn over 150, fail over 300", () => {
    expect(SKILL_LINE_WARN).toBe(150);
    expect(SKILL_LINE_FAIL).toBe(300);
  });

  test("a short skill body produces nothing", () => {
    expect(checkBudget(ctxFor({ "skills/alpha/SKILL.md": OK }))).toEqual([]);
  });

  test("over the warn limit is a warning", () => {
    const body = `---\nname: alpha\ndescription: d\n---\n${"line\n".repeat(SKILL_LINE_WARN + 1)}`;
    const issues = checkBudget(ctxFor({ "skills/alpha/SKILL.md": body }));
    expect(issues[0]?.severity).toBe("warning");
    expect(issues[0]?.rule).toBe("budget.skill-over-target");
  });

  test("over the hard cap is an error", () => {
    const body = `---\nname: alpha\ndescription: d\n---\n${"line\n".repeat(SKILL_LINE_FAIL + 1)}`;
    const issues = checkBudget(ctxFor({ "skills/alpha/SKILL.md": body }));
    expect(issues[0]?.severity).toBe("error");
    expect(issues[0]?.rule).toBe("budget.skill-over-cap");
    expect(issues[0]?.message).toContain(String(SKILL_LINE_FAIL));
  });

  test("exactly at the warn limit is clean", () => {
    const body = `---\nname: alpha\ndescription: d\n---\n${"line\n".repeat(SKILL_LINE_WARN - 4)}`;
    expect(checkBudget(ctxFor({ "skills/alpha/SKILL.md": body }))).toEqual([]);
  });
});

/**
 * §12 says §1 applies to protocol and role bodies unchanged, and the budget
 * check read only `SKILL.md`. The cost was concrete: a 151-line protocol body
 * got a formal exception record written for a threshold the validator never
 * applied to it.
 */
describe("the line budget reaches every body §1 governs", () => {
  function bodyCtx(files: Record<string, string>) {
    const root = makeTree({
      "catalog.yaml": `schema_version: 1\npackage:\n  id: ak\n  name: agent-kit\n  version: 0.1.0\n  namespace: "/ak:"\n  default_profile: core\nprotocols:\n  - id: alpha\n    status: authored\nroles:\n  - id: beta\n    status: authored\n`,
      ...files,
    });
    const { catalog } = loadCatalog(root);
    if (catalog === null) throw new Error("fixture has no catalog");
    return { root, catalog };
  }

  test("a protocol body over the target is a warning, as §1 says it is", () => {
    const issues = checkBudget(bodyCtx({ "protocols/alpha/PROTOCOL.md": "line\n".repeat(SKILL_LINE_WARN + 1) }));
    expect(issues[0]?.rule).toBe("budget.body-over-target");
    expect(issues[0]?.severity).toBe("warning");
    expect(issues[0]?.file).toBe("protocols/alpha/PROTOCOL.md");
  });

  test("a role body over the hard cap is an error", () => {
    const issues = checkBudget(bodyCtx({ "roles/beta/ROLE.md": "line\n".repeat(SKILL_LINE_FAIL + 1) }));
    expect(issues[0]?.rule).toBe("budget.body-over-cap");
    expect(issues[0]?.severity).toBe("error");
  });

  test("a body inside the target produces nothing", () => {
    expect(checkBudget(bodyCtx({ "protocols/alpha/PROTOCOL.md": "line\n".repeat(20) }))).toEqual([]);
  });
});
