import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";

import { DENY_TERMS, PLACEHOLDER_TERMS, matchTerms } from "../src/denylist.ts";
import { runValidation } from "../src/validation/run.ts";
import type { Issue } from "../src/validation/types.ts";
import { materializeFixture } from "./helpers/tree.ts";

/**
 * One deliberately-broken tree per case, each the smallest repository that can
 * hold the mistake. `rules` is the complete set of error rules the tree may
 * raise, so a fixture that starts failing for a second reason fails the test
 * rather than passing on the one rule it was written for.
 */
interface InvalidCase {
  tree: string;
  what: string;
  rule: string;
  file: string;
  message: RegExp;
  rules?: string[];
}

const CASES: ReadonlyArray<InvalidCase> = [
  {
    tree: "01-catalog-entry-without-directory",
    what: "a catalog entry with no directory",
    rule: "catalog.entry-without-directory",
    file: "skills/alpha",
    message: /declares skills\/alpha as authored but skills\/alpha\/ does not exist/,
  },
  {
    tree: "02-directory-without-catalog-entry",
    what: "a directory with no catalog entry",
    rule: "catalog.directory-without-entry",
    file: "skills/ghost",
    message: /catalog\.yaml declares no skills entry 'ghost'/,
  },
  {
    tree: "03-broken-link-source",
    what: "a relative link that does not resolve in the source tree",
    rule: "links.broken-source",
    file: "skills/alpha/SKILL.md",
    message: /'references\/guide\/REFERENCE\.md' does not exist/,
    // A link that is dangling at the source is dangling in the bundle too.
    rules: ["links.broken-source", "links.broken-bundle"],
  },
  {
    tree: "04-broken-link-bundle",
    what: "a link that resolves in the source tree and breaks after packaging",
    rule: "links.broken-bundle",
    file: "dist/claude-code/references/shared/references/guide/REFERENCE.md",
    message: /'references\/shared\/protocols\/review' is not in the claude-code bundle/,
  },
  {
    tree: "05-model-name-in-body",
    what: "a model name in a skill body",
    rule: "content.denylist",
    file: "skills/alpha/SKILL.md",
    message: /Denied term/,
  },
  {
    tree: "06-placeholder-text",
    what: "an unfinished marker in an authored body",
    rule: "content.placeholder",
    file: "skills/alpha/SKILL.md",
    message: /in an authored body/,
  },
  {
    tree: "07-u-calls-u",
    what: "a user-invoked skill starting another user-invoked skill",
    rule: "invocation.u-calls-u",
    file: "skills/alpha/SKILL.md",
    message: /starts user-invoked skill 'beta' directly/,
  },
  {
    tree: "08-missing-provenance",
    what: "an adapted directory with no provenance row",
    rule: "provenance.missing-adaptation",
    file: "skills/alpha",
    message: /declares provenance_origin: donor but no row in provenance\/adaptations\.yaml/,
  },
  {
    tree: "09-smell-with-difficulty",
    what: "a finding whose solution space is open carrying a difficulty",
    rule: "finding.difficulty-on-open-solution-space",
    file: "templates/finding.json",
    message: /difficulty is 'mechanical'/,
  },
  {
    tree: "10-stale-approval",
    what: "an approval that no longer binds the artifact it approved",
    rule: "approval.stale",
    file: "templates/review.json",
    message: /does not inherit the previous approval/,
  },
  {
    tree: "11-decision-ticket-dispatched",
    what: "a decision ticket dispatched as implementation work",
    rule: "ticket.decision-dispatched-as-implementation",
    file: "templates/ticket.json",
    message: /carries implementation field\(s\) write_ownership/,
  },
  {
    tree: "12-self-closed-finding",
    what: "an author closing their own finding",
    rule: "finding.self-closed",
    file: "templates/finding.json",
    message: /An author may never close their own finding/,
  },
  {
    tree: "13-forged-grant",
    what: "a grant naming a charter that does not exist",
    rule: "grant.charter-hash-unknown",
    file: "templates/ticket.json",
    message: /matches no charter artifact/,
  },
  {
    tree: "14-host-key-in-canonical",
    what: "a host frontmatter key hand-written into a canonical SKILL.md",
    rule: "frontmatter.host-key-in-canonical",
    file: "skills/alpha/SKILL.md",
    message: /generated by the packager .* must not appear in a canonical SKILL\.md/,
  },
];

function errorsOf(tree: string): Issue[] {
  return runValidation(materializeFixture(tree)).issues.filter((i) => i.severity === "error");
}

describe("the positive fixture", () => {
  test("a minimal well-formed tree validates clean", () => {
    const run = runValidation(materializeFixture("valid/minimal"));
    const loud = run.issues.filter((i) => i.severity !== "note");
    expect(loud.map((i) => `${i.rule} ${i.file}`)).toEqual([]);
    expect(run.ok).toBe(true);
  });

  test("the notes it does emit name the absent inputs rather than crashing", () => {
    const run = runValidation(materializeFixture("valid/minimal"));
    expect(run.issues.map((i) => i.rule)).toContain("provenance.lock-unavailable");
    expect(run.issues.map((i) => i.rule)).toContain("policy.invocation-unavailable");
  });
});

describe("invalid fixtures", () => {
  for (const c of CASES) {
    test(`${c.tree}: ${c.what}`, () => {
      const errors = errorsOf(`invalid/${c.tree}`);
      const hit = errors.find((i) => i.rule === c.rule && i.file === c.file);
      expect({
        tree: c.tree,
        found: hit !== undefined,
        rules: [...new Set(errors.map((i) => i.rule))].sort(),
      }).toEqual({
        tree: c.tree,
        found: true,
        rules: [...new Set(c.rules ?? [c.rule])].sort(),
      });
      expect(hit?.message).toMatch(c.message);
    });
  }

  test("every committed invalid fixture has a case asserting what it must report", () => {
    const dir = join(import.meta.dir, "fixtures", "invalid");
    const trees = readdirSync(dir).filter((n) => statSync(join(dir, n)).isDirectory());
    expect(trees.sort()).toEqual(CASES.map((c) => c.tree).sort());
  });
});

describe("the fixtures do not smuggle denied strings into the tree", () => {
  function fixtureFiles(dir: string): string[] {
    const out: string[] = [];
    for (const name of readdirSync(dir)) {
      const full = join(dir, name);
      if (statSync(full).isDirectory()) out.push(...fixtureFiles(full));
      else out.push(full);
    }
    return out;
  }

  test("no committed fixture file contains a denied term or an unfinished marker", () => {
    const terms = [...DENY_TERMS, ...PLACEHOLDER_TERMS];
    const hits: string[] = [];
    for (const file of fixtureFiles(join(import.meta.dir, "fixtures"))) {
      for (const hit of matchTerms(readFileSync(file, "utf8"), terms)) {
        hits.push(`${file}:${hit.line} ${hit.term.id}`);
      }
    }
    expect(hits).toEqual([]);
  });

  test("materializing a fixture substitutes the markers, so the scanner sees the real strings", () => {
    const body = readFileSync(join(materializeFixture("invalid/05-model-name-in-body"), "skills/alpha/SKILL.md"), "utf8");
    expect(body).not.toContain("__DENY_MODEL_TERM__");
    expect(matchTerms(body, DENY_TERMS).length).toBeGreaterThan(0);
  });
});
