import { join } from "node:path";

import { entryBodyPath } from "../catalog/layout.ts";
import { readTextIfPresent } from "../util/fs.ts";
import { parseFrontmatter } from "../util/frontmatter.ts";
import type { CheckContext } from "./context.ts";
import { error, type Issue } from "./types.ts";

/** The whole Agent Skills frontmatter vocabulary a canonical SKILL.md may carry. */
export const AGENT_SKILLS_KEYS: ReadonlySet<string> = new Set(["name", "description", "license", "metadata"]);

/** Emitted by the packager from skill.yaml. Hand-writing one is a validation failure. */
export const HOST_GENERATED_KEYS: ReadonlySet<string> = new Set([
  "disable-model-invocation",
  "argument-hint",
  "allowed-tools",
]);

const REQUIRED_KEYS = ["name", "description"] as const;

export function checkFrontmatter(ctx: CheckContext): Issue[] {
  const issues: Issue[] = [];

  for (const entry of ctx.catalog.bySection("skills")) {
    const file = entryBodyPath("skills", entry.id);
    const text = readTextIfPresent(join(ctx.root, file));
    if (text === null) continue; // completeness owns "the body does not exist yet".

    const fm = parseFrontmatter(text);
    if (!fm.present) {
      issues.push(error("frontmatter.missing", file, "A canonical SKILL.md must open with a YAML frontmatter block."));
      continue;
    }
    if (fm.error !== undefined) {
      issues.push(error("frontmatter.unparseable", file, `Frontmatter YAML is invalid: ${fm.error}`));
      continue;
    }

    for (const key of Object.keys(fm.data)) {
      const line = fm.keyLines[key];
      if (HOST_GENERATED_KEYS.has(key)) {
        issues.push(
          error(
            "frontmatter.host-key-in-canonical",
            file,
            `'${key}' is generated by the packager from skill.yaml and must not appear in a canonical SKILL.md.`,
            line,
          ),
        );
      } else if (!AGENT_SKILLS_KEYS.has(key)) {
        issues.push(
          error(
            "frontmatter.unknown-key",
            file,
            `'${key}' is not an Agent Skills spec key. Canonical frontmatter carries only ${[...AGENT_SKILLS_KEYS].join(", ")}.`,
            line,
          ),
        );
      }
    }

    for (const key of REQUIRED_KEYS) {
      if (fm.data[key] === undefined) {
        issues.push(error("frontmatter.missing-required-key", file, `Frontmatter is missing required key '${key}'.`));
      }
    }

    const name = fm.data["name"];
    if (typeof name === "string" && name !== entry.id) {
      issues.push(
        error(
          "frontmatter.name-mismatch",
          file,
          `Frontmatter name is '${name}' but the directory is '${entry.id}'; name must equal the directory name.`,
          fm.keyLines["name"],
        ),
      );
    }
  }

  return issues;
}
