import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { readTextIfPresent, walkFiles } from "../util/fs.ts";
import type { CheckContext } from "../validation/context.ts";
import { error, type Issue } from "../validation/types.ts";
import { ADAPTATIONS_FILE, loadAdaptationFragments, renderAdaptations } from "../validation/provenance.ts";
import { HOST_IDS, type HostId } from "./hosts.ts";
import { planBundle, type BundlePlan, type PlanOptions } from "./plan.ts";

export interface BuildOptions extends PlanOptions {
  hosts?: ReadonlyArray<HostId>;
}

export function planAll(ctx: CheckContext, options: BuildOptions): BundlePlan[] {
  return (options.hosts ?? HOST_IDS).map((host) => planBundle(ctx, host, options));
}

function distDir(host: HostId): string {
  return `dist/${host}`;
}

export function writeBundles(ctx: CheckContext, options: BuildOptions): Issue[] {
  const issues: Issue[] = [];

  for (const plan of planAll(ctx, options)) {
    issues.push(...plan.issues);
    const outRoot = join(ctx.root, distDir(plan.host));
    rmSync(outRoot, { recursive: true, force: true });
    for (const file of plan.files.values()) {
      const target = join(outRoot, file.path);
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, file.contents);
    }
  }

  return issues;
}

/** Verify dist/ matches what a build would emit. Writes nothing. */
export function checkBundles(ctx: CheckContext, options: BuildOptions): Issue[] {
  const issues: Issue[] = [];

  for (const plan of planAll(ctx, options)) {
    issues.push(...plan.issues);
    const dir = distDir(plan.host);
    const onDisk = new Set(walkFiles(ctx.root, dir).map((p) => p.slice(dir.length + 1)));

    for (const file of plan.files.values()) {
      const actual = readTextIfPresent(join(ctx.root, dir, file.path));
      if (actual === null) {
        issues.push(error("packaging.dist-missing", `${dir}/${file.path}`, "Generated by ak build but absent from dist/. Run ak build."));
        continue;
      }
      onDisk.delete(file.path);
      if (actual !== file.contents) {
        issues.push(error("packaging.dist-stale", `${dir}/${file.path}`, "Content differs from what ak build would emit. Run ak build."));
      }
    }

    for (const extra of [...onDisk].sort()) {
      issues.push(error("packaging.dist-extra", `${dir}/${extra}`, "Present in dist/ but not generated by ak build. Run ak build."));
    }
  }

  return issues;
}

/**
 * Render provenance/adaptations.yaml from its fragments.
 *
 * This is a source-tree artifact rather than a bundle file: NOTICE, README,
 * AGENTS.md and catalog.yaml all point at the path, so it is generated and
 * committed. It is written before the bundles and independently of them, so a
 * tree whose skills are not yet authored still gets a correct attribution file.
 * Conflicting fragments stop the write: half a merge is worse than none.
 */
export function writeAdaptations(ctx: CheckContext): Issue[] {
  const { rows, issues } = loadAdaptationFragments(ctx.root);
  if (issues.some((i) => i.severity === "error")) return issues.filter((i) => i.severity === "error");

  const target = join(ctx.root, ADAPTATIONS_FILE);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, renderAdaptations(rows));
  return [];
}
